sackbot:
  bot:
    token: NjgxNTQwMzE3MTE5MzgxNTM0.XlvTkw.aC0wzxtEwoCjRH3p1Kbl6ddcDZ4
    activity:
      type: watching
      text: hottest memes
    chat:
      enabled: true
      allowDm: true
      commandPrefix: /
  files:
    folder: ${user.home}${file.separator}sackbot${file.separator}sounds
    watcher:
      enabled: true
  nitrite:
    dbFile: ${user.home}${file.separator}sacbot${file.separator}database.db

logging:
  level:
    com.github.sipe90.sackbot: debug