sackbot:
  bot:
    token: bot_token
    activity:
      type: watching
      text: hottest memes
    chat:
      enabled: true
      allowDm: true
      commandPrefix: /
  files:
    folder: ${user.home}${file.separator}sackbot${file.separator}sounds
    watcher:
      enabled: true
  nitrite:
    dbFile: ${user.home}${file.separator}sackbot${file.separator}database.db
