name: Gradle Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        description: Release version
        required: true
      new-version:
        type: string
        description: New snapshot version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Build image with JIB and push it to Docker Hub
        run: ./gradlew release
          -Prelease.useAutomaticVersion=true
          -Prelease.releaseVersion=${{ github.event.inputs.release-version }}
          -Prelease.newVersion=${{ github.event.inputs.new-version }}
          -Djib.console=plain
          -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }}
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        with:
          args: build/libs/sack-bot-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
