name: Gradle Release

on:
  workflow_dispatch:
    inputs:
      type:
        default: final
        type: choice
        description: Release type (final or release candidate).
        required: false
        options:
          - final
          - candidate
      scope:
        default: minor
        type: choice
        description: Release scope (major, minor or patch)
        required: false
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Boot Jar and Docker image and push image to Docker Hub
        run: ./gradlew bootJar ${{ github.event.inputs.type }}
          -Prelease.scope=${{ github.event.inputs.scope }}
          -Pdocker.publishRegistry.username=${{ secrets.DOCKERHUB_USERNAME }}
          -Pdocker.publishRegistry.password=${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        with:
          args: build/libs/sack-bot-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
